demo/demo/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url,include
from demoapp import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('demoapp.urls')),
    path('',views.index,name='index'),
    path('logout/',views.user_logout,name='logout'),
    path('special/',views.special,name='special'),
]

demo/demoapp/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url,include
from demoapp import views

app_name='demoapp'

urlpatterns = [
    path('dash/',views.dash,name='dash'),
    path('org/',views.org_form,name='org_form'),
    path('Adm',views.admin_form,name='admin_form'),
    path('emp/',views.emp_form,name='emp_form'),
    path('mng/',views.mang_form,name='mang_form'),
    path('task/',views.task_form,name='task_form'),
    path('work/',views.work_form,name='work_form'),
    path('dep/',views.dep_form,name='dep_form'),
    path('clients/',views.client_form,name='client_form'),
    path('dash2/',views.dash2,name='dash2'),
    path('dash3/',views.dash3,name='dash3'),
    path('dash4/',views.dash4,name='dash4'),
    path('dash5/',views.dash5,name='dash5'),
    path('register/',views.register,name='register'),
    path('login/',views.user_login,name='user_login'),
    path('tab/',views.table,name='tab'),
]

demo/Dept/models.py
from django.db import models

# Create your models here.

demo/demoapp/forms.py
from django import forms
from django.core  import validators
from demoapp.models import Organisation,Admin,Manager,Department,Employee,Task,Client,Work,UserProfileInfo
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm


class Organisation_form(forms.ModelForm):
     class Meta:
        model =  Organisation
        fields = '__all__'

    



class Admin_form(forms.ModelForm):
    class Meta:
        model = Admin
        fields = '__all__'   






class Manager_form(forms.ModelForm):
    class Meta:    
       model = Manager
       fields = '__all__' 






class Client_form(forms.ModelForm):
    class Meta:    
        model = Client
        fields = '__all__' 






class Employee_form(forms.ModelForm):
    class Meta:
           model = Employee
           fields = '__all__' 






class Task_form(forms.ModelForm):
    class Meta:
         model = Task
         fields = '__all__' 






class Work_form(forms.ModelForm):
    class Meta:
           model = Work
           fields = '__all__' 





class Department_form(forms.ModelForm):
    class Meta:
           model = Department
           fields = '__all__' 




class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())
    class Meta():
        model = User
        fields = ('username','email','password')


class UserProfileInfoForm(forms.ModelForm):
    class Meta():
        model = UserProfileInfo
        fields = ('profile_pic','portfolio_site')

  

demo/Dept/views.py
from django.shortcuts import render

# Create your views here.

demo/demoapp/views.py
from django.shortcuts import render
from demoapp.forms import Organisation_form,Admin_form,Manager_form,Client_form,Employee_form,Task_form, Work_form,Department_form,UserForm,UserProfileInfoForm
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse,HttpResponseRedirect
from django.contrib.auth import authenticate,login,logout

# Create your views here.
def index(request):
    return render (request,'demoapp/index.html')


def table(request):
    return render(request,'demoapp/jsgrid.html')


@login_required
def special(request):
    return HttpResponse('You are logged in nice!')


@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('demoapp:dash'))


def dash(request):
    return render(request,'demoapp/Dashboard.html')


def dash2(request):
    return render(request,'demoapp/Dashboard2.html')



def dash3(request):
    return render(request,'demoapp/dashboard_dept.html')

def dash4(request):
    return render(request,'demoapp/dashboard_task.html')

def dash5(request):
    return render(request,'demoapp/dashboard_work.html')

def dep_form(request):
    form = Department_form()


    if request.method =='POST':
        form = Department_form(request.POST)


        if form.is_valid():
            form.save(commit=True)
            return index(request)


        else:
            print("ERROR!")   


    return render(request,'demoapp/dept.html',{'form':form}) 





def admin_form(request):
    form = Admin_form()


    if request.method =='POST':
        form = Admin_form(request.POST)


        if form.is_valid():
            form.save(commit=True)
            return index(request)


        else:
            print("ERROR!")   


    return render(request,'demoapp/login.html',{'form':form}) 
            


def mang_form(request):
    form = Manager_form()


    if request.method =='POST':
        form = Manager_form(request.POST)


        if form.is_valid():
            form.save(commit=True)
            return index(request)


        else:
            print("ERROR!")   


    return render(request,'demoapp/login.html',{'form':form}) 




def client_form(request):
    form = Client_form()


    if request.method =='POST':
        form = Client_form(request.POST)


        if form.is_valid():
            form.save(commit=True)
            return index(request)


        else:
            print("ERROR!")   


    return render(request,'demoapp/form_page.html',{'form':form}) 




def org_form(request):
    form = Organisation_form()


    if request.method =='POST':
        form = Organisation_form(request.POST)


        if form.is_valid():
            form.save(commit=True)
            return index(request)


        else:
            print("ERROR!")   


    return render(request,'demoapp/login.html',{'form':form}) 




def emp_form(request):
    form = Employee_form()


    if request.method =='POST':
        form =Employee_form(request.POST)


        if form.is_valid():
            form.save(commit=True)
            return index(request)


        else:
            print("ERROR!")   


    return render(request,'demoapp/login.html',{'form':form}) 




def work_form(request):
    form = Work_form()


    if request.method =='POST':
        form =Work_form(request.POST)


        if form.is_valid():
            form.save(commit=True)
            return index(request)


        else:
            print("ERROR!")   


    return render(request,'demoapp/login.html',{'form':form}) 





def task_form(request):
    form = Task_form()


    if request.method =='POST':
        form =Task_form(request.POST)


        if form.is_valid():
            form.save(commit=True)
            return index(request)


        else:
            print("ERROR!")   


    return render(request,'demoapp/task.html',{'form':form}) 




def register(request):

    registered = False

    if request.method == 'POST':
        user_form = UserForm(request.POST)
        profile_form = UserProfileInfoForm(request.POST)
        



        if user_form.is_valid() and profile_form.is_valid():

            user = user_form.save()
            user.set_password(user.password)
            user.save()



            profile = profile_form.save(commit = False)
            profile.user = user


            if 'profile_pic' in request.FILES:
                profile.profile_pic = request.FILES['profile_pic']
            profile.save()
            

            registered = True


        else:
            print(user_form.errors,profile_form.errors)

    else:
        user_form = UserForm()
        profile_form = UserProfileInfoForm()

    return render(request,'demoapp/registration.html',{'user_form':user_form,'profile_form':profile_form,'registered':registered})



def user_login(request):



    if request.method =='POST':
        username = request.POST.get('username')
        password = request.POST.get('password')



        user = authenticate(username=username,password=password)


        if user:
            if user.is_active:
                login(request,user)
                return HttpResponseRedirect(reverse('demoapp:dash'))


            else:
                return HttpResponse("ACCOUNT NOT ACTIVE")


        else:
            print("Someone tried to login and Failed!")
            print("Username: {} and password {}".format(username,password) ) 
            return HttpResponse("invalid login details supplied!")

    else:
        return render(request,'demoapp/login.html',{})    

demo/templates/demoapp/Dashboard2.html
<!DOCTYPE html>
{% extends 'demoapp/Dashboard.html' %}
{%load static%}
<html lang="en">
<head>
 
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">

  <title>Teccstart</title>
  <!-- jsGrid -->
  <link rel="stylesheet" href="{%static "ADMINLTE/plugins/jsgrid/jsgrid.min.css" %}">
  <link rel="stylesheet" href="{%static "ADMINLTE/plugins/jsgrid/jsgrid-theme.min.css" %}">
  <!-- Ionicons -->
  <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
  <!-- Tempusdominus Bbootstrap 4 -->
  <link rel="stylesheet" href="{%static "ADMINLTE/plugins/tempusdominus-bootstrap-4/css/tempusdominus-bootstrap-4.min.css" %}">
  <!-- iCheck -->
  <link rel="stylesheet" href="{%static "ADMINLTE/plugins/icheck-bootstrap/icheck-bootstrap.min.css" %}">
  <!-- JQVMap -->
  <link rel="stylesheet" href="{%static "ADMINLTE/plugins/jqvmap/jqvmap.min.css"  %}">
  <!-- Favicon-->
  <link rel="icon" type="image/png" href="static/landing_page/js/logo.png"   />
  <title>Teecstart</title>
  <!-- Font Awesome Icons -->
  <link rel="stylesheet" href="{%static "ADMINLTE/plugins/fontawesome-free/css/all.min.css" %}">
  <!-- overlayScrollbars -->
  <link rel="stylesheet" href="{%static "ADMINLTE/plugins/overlayScrollbars/css/OverlayScrollbars.min.css" %}">
  <!-- Theme style -->
  <link rel="stylesheet" href="{%static "ADMINLTE/dist/css/adminlte.min.css" %}">
  <!-- Google Font: Source Sans Pro -->
  <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">
   <!-- Daterange picker -->
   <link rel="stylesheet" href="{%static "ADMINLTE/plugins/daterangepicker/daterangepicker.css" %}">
   <!-- summernote -->
   <link rel="stylesheet" href="{%static "ADMINLTE/plugins/summernote/summernote-bs4.css" %}">
</head>
<body>
  {%block body_block%}
  <!-- Main content -->
    <section class="content">
      <div class="container-fluid">
        <!-- Info boxes -->
        <div class="row">
          <div class="col-12 col-sm-6 col-md-3">
            <div class="info-box">
              <span class="info-box-icon bg-info elevation-1"><i class="fas fa-cog"></i></span>

              <div class="info-box-content">
                <span class="info-box-text">CPU Traffic</span>
                <span class="info-box-number">
                  10
                  <small>%</small>
                </span>
              </div>
              <!-- /.info-box-content -->
            </div>
            <!-- /.info-box -->
          </div>
          <!-- /.col -->
          <div class="col-12 col-sm-6 col-md-3">
            <div class="info-box mb-3">
              <span class="info-box-icon bg-danger elevation-1"><i class="fas fa-thumbs-up"></i></span>

              <div class="info-box-content">
                <span class="info-box-text">Likes</span>
                <span class="info-box-number">41,410</span>
              </div>
              <!-- /.info-box-content -->
            </div>
            <!-- /.info-box -->
          </div>
          <!-- /.col -->

          <!-- fix for small devices only -->
          <div class="clearfix hidden-md-up"></div>

          <div class="col-12 col-sm-6 col-md-3">
            <div class="info-box mb-3">
              <span class="info-box-icon bg-success elevation-1"><i class="fas fa-shopping-cart"></i></span>

              <div class="info-box-content">
                <span class="info-box-text">Sales</span>
                <span class="info-box-number">760</span>
              </div>
              <!-- /.info-box-content -->
            </div>
            <!-- /.info-box -->
          </div>
          <!-- /.col -->
          <div class="col-12 col-sm-6 col-md-3">
            <div class="info-box mb-3">
              <span class="info-box-icon bg-warning elevation-1"><i class="fas fa-users"></i></span>

              <div class="info-box-content">
                <span class="info-box-text">New Members</span>
                <span class="info-box-number">2,000</span>
              </div>
              <!-- /.info-box-content -->
            </div>
            <!-- /.info-box -->
          </div>
          <!-- /.col -->
        </div>
        <!-- /.row -->
{% block client_block %}

<a href="{%url 'demoapp:client_form' %}" class="btn btn-primary" >Add Clients</a>
{% endblock %}


  


<!-- REQUIRED SCRIPTS -->
<!-- jQuery -->
<script src="{%static "ADMINLTE/plugins/jquery/jquery.min.js" %}"></script>
<!-- Bootstrap -->
<script src="{%static "ADMINLTE/ADMINLTE/plugins/bootstrap/js/bootstrap.bundle.min.js" %}"></script>
<!-- overlayScrollbars -->
<script src="{%static "ADMINLTE/plugins/overlayScrollbars/js/jquery.overlayScrollbars.min.js" %}"></script>
<!-- AdminLTE App -->
<script src="{%static "ADMINLTE/dist/js/adminlte.js" %}"></script>

<!-- OPTIONAL SCRIPTS -->
<script src="{%static "ADMINLTE/dist/js/demo.js" %}"></script>

<!-- PAGE PLUGINS -->
<!-- jQuery Mapael -->
<script src="{%static "ADMINLTE/plugins/jquery-mousewheel/jquery.mousewheel.js" %}"></script>
<script src="{%static "ADMINLTE/plugins/raphael/raphael.min.js" %}"></script>
<script src="{%static "ADMINLTE/plugins/jquery-mapael/jquery.mapael.min.js" %}"></script>
<script src="{%static "ADMINLTE/plugins/jquery-mapael/maps/usa_states.min.js" %}"></script>
<!-- ChartJS -->
<script src="{%static "ADMINLTE/plugins/chart.js/Chart.min.js" %}"></script>

<!-- PAGE SCRIPTS -->
<script src={%static "ADMINLTE/dist/js/pages/dashboard2.js" %}"></script> 
{% endblock %}
</div>
</body>
</html>

demo/templates/demoapp/dashboard_work.html
<!DOCTYPE html>
{% extends 'demoapp/Dashboard2.html'  %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    {% block client_block %}
    <a href="{%url 'demoapp:work_form' %}" class="btn btn-primary" >Add work</a>
  
    {% endblock %}
</body>
</html>

demo/templates/demoapp/form_page.html
<!DOCTYPE html>
<html lang="en">
<head>
    <style>
    h1{text-align: center;}
    p{text-align: center;}
    </style>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Forms</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
</head>
<body>

    <h1> Fill out the Form!</h1>
    <div class="container-fluid">
        <div class = "jumbotron">
        <h1>Please SignUp Here </h1>
        <form  method="post">
            {{form.as_p}}
            {% csrf_token %}
            <input type="submit" class="btn btn-outline-warning" value="submit">
        </form>
    </div>
  </div>
</body>
</html>

demo/templates/demoapp/lockscreen.html
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>AdminLTE 3 | Lockscreen</title>
  <!-- Tell the browser to be responsive to screen width -->
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <!-- Font Awesome -->
  <link rel="stylesheet" href="../../plugins/fontawesome-free/css/all.min.css">
  <!-- Ionicons -->
  <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
  <!-- Theme style -->
  <link rel="stylesheet" href="../../dist/css/adminlte.min.css">
  <!-- Google Font: Source Sans Pro -->
  <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">
</head>
<body class="hold-transition lockscreen">
<!-- Automatic element centering -->
<div class="lockscreen-wrapper">
  <div class="lockscreen-logo">
    <a href="../../index2.html"><b>Admin</b>LTE</a>
  </div>
  <!-- User name -->
  <div class="lockscreen-name">John Doe</div>

  <!-- START LOCK SCREEN ITEM -->
  <div class="lockscreen-item">
    <!-- lockscreen image -->
    <div class="lockscreen-image">
      <img src="../../dist/img/user1-128x128.jpg" alt="User Image">
    </div>
    <!-- /.lockscreen-image -->

    <!-- lockscreen credentials (contains the form) -->
    <form class="lockscreen-credentials">
      <div class="input-group">
        <input type="password" class="form-control" placeholder="password">

        <div class="input-group-append">
          <button type="button" class="btn"><i class="fas fa-arrow-right text-muted"></i></button>
        </div>
      </div>
    </form>
    <!-- /.lockscreen credentials -->

  </div>
  <!-- /.lockscreen-item -->
  <div class="help-block text-center">
    Enter your password to retrieve your session
  </div>
  <div class="text-center">
    <a href="login.html">Or sign in as a different user</a>
  </div>
  <div class="lockscreen-footer text-center">
    Copyright &copy; 2014-2019 <b><a href="http://adminlte.io" class="text-black">AdminLTE.io</a></b><br>
    All rights reserved
  </div>
</div>
<!-- /.center -->

<!-- jQuery -->
<script src="../../plugins/jquery/jquery.min.js"></script>
<!-- Bootstrap 4 -->
<script src="../../plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
</body>
</html>

demo/templates/demoapp/login.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>Teccstart | Log in</title>
  <!-- Tell the browser to be responsive to screen width -->
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <!-- Font Awesome -->
  <link rel="stylesheet" href="{%static "ADMINLTE/plugins/fontawesome-free/css/all.min.css" %}">
  <!-- Ionicons -->
  <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css"  >
  <!-- icheck bootstrap -->
  <link rel="stylesheet" href="{%static "ADMINLTE/plugins/icheck-bootstrap/icheck-bootstrap.min.css" %}">
  <!-- Theme style -->
  <link rel="stylesheet" href="{%static "ADMINLTE/dist/css/adminlte.min.css" %}">
  <!-- Google Font: Source Sans Pro -->
  <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">
</head>
<body class="hold-transition login-page">
<div class="login-box">
  <div class="login-logo">
    <a href="{% url "index"  %}">Teccstart</a>
  </div>
  <!-- /.login-logo -->
  <div class="card">
    <div class="card-body login-card-body">
      <p class="login-box-msg"></p>

      <form action="{% url 'demoapp:user_login' %}" method="post">
              {%  csrf_token %}
       <li><label for='username' >UserName:</label></li> 
        <input type='text' name='username' placeholder="Enter username">
        
       <li> <label for='password'>Password:</label></li>
        <input type='password' name='password' >
       <div class="row">
          <div class="col-8">
            <div class="icheck-primary">
              <input type="checkbox" id="remember">
              <label for="remember">
                Remember Me
              </label>
            </div>
          </div>
          <!-- /.col -->
          <div class="col-4">
            <button type="submit" class="btn btn-primary btn-block" ><a>Log In</a></button>
          </div>
          <!-- /.col -->
        </div>
      </form>

    <p class="mb-1">
        <a href="forgot-password.html">I forgot my password</a>
      </p>
      <p class="mb-0">
        <a href="{% url 'demoapp:register' %}" class="text-center">Register a new membership</a>
      </p>
    </div>
    <!-- /.login-card-body -->
  </div>
</div>
<!-- /.login-box -->

<!-- jQuery -->
<script src="static/ADMINLTE/plugins/jquery/jquery.min.js"></script>
<!-- Bootstrap 4 -->
<script src="static/ADMINLTE/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
<!-- AdminLTE App -->
<script src="static/ADMINLTE/dist/js/adminlte.min.js"></script>

</body>
</html> 

demo/templates/demoapp/recover-password.html
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>AdminLTE 3 | Recover Password</title>
  <!-- Tell the browser to be responsive to screen width -->
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <!-- Font Awesome -->
  <link rel="stylesheet" href="../../plugins/fontawesome-free/css/all.min.css">
  <!-- Ionicons -->
  <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
  <!-- icheck bootstrap -->
  <link rel="stylesheet" href="../../plugins/icheck-bootstrap/icheck-bootstrap.min.css">
  <!-- Theme style -->
  <link rel="stylesheet" href="../../dist/css/adminlte.min.css">
  <!-- Google Font: Source Sans Pro -->
  <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">
</head>
<body class="hold-transition login-page">
<div class="login-box">
  <div class="login-logo">
    <a href="../../index2.html"><b>Admin</b>LTE</a>
  </div>
  <!-- /.login-logo -->
  <div class="card">
    <div class="card-body login-card-body">
      <p class="login-box-msg">You are only one step a way from your new password, recover your password now.</p>

      <form action="login.html" method="post">
        <div class="input-group mb-3">
          <input type="password" class="form-control" placeholder="Password">
          <div class="input-group-append">
            <div class="input-group-text">
              <span class="fas fa-lock"></span>
            </div>
          </div>
        </div>
        <div class="input-group mb-3">
          <input type="password" class="form-control" placeholder="Confirm Password">
          <div class="input-group-append">
            <div class="input-group-text">
              <span class="fas fa-lock"></span>
            </div>
          </div>
        </div>
        <div class="row">
          <div class="col-12">
            <button type="submit" class="btn btn-primary btn-block">Change password</button>
          </div>
          <!-- /.col -->
        </div>
      </form>

      <p class="mt-3 mb-1">
        <a href="login.html">Login</a>
      </p>
    </div>
    <!-- /.login-card-body -->
  </div>
</div>
<!-- /.login-box -->

<!-- jQuery -->
<script src="../../plugins/jquery/jquery.min.js"></script>
<!-- Bootstrap 4 -->
<script src="../../plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
<!-- AdminLTE App -->
<script src="../../dist/js/adminlte.min.js"></script>

</body>
</html>

demo/templates/demoapp/register.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>AdminLTE 3 | Registration Page</title>
  <!-- Tell the browser to be responsive to screen width -->
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <!-- Font Awesome -->
  <link rel="stylesheet" href="../../plugins/fontawesome-free/css/all.min.css">
  <!-- Ionicons -->
  <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
  <!-- icheck bootstrap -->
  <link rel="stylesheet" href="../../plugins/icheck-bootstrap/icheck-bootstrap.min.css">
  <!-- Theme style -->
  <link rel="stylesheet" href="../../dist/css/adminlte.min.css">
  <!-- Google Font: Source Sans Pro -->
  <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">
</head>
<body class="hold-transition register-page">
<div class="register-box">
  <div class="register-logo">
    <a href="../../index2.html"><b>Admin</b>LTE</a>
  </div>

  <div class="card">
    <div class="card-body register-card-body">
      <p class="login-box-msg">Register a new membership</p>

      <form action="../../index.html" method="post">
        <div class="input-group mb-3">
          <input type="text" class="form-control" placeholder="Full name">
          <div class="input-group-append">
            <div class="input-group-text">
              <span class="fas fa-user"></span>
            </div>
          </div>
        </div>
        <div class="input-group mb-3">
          <input type="email" class="form-control" placeholder="Email">
          <div class="input-group-append">
            <div class="input-group-text">
              <span class="fas fa-envelope"></span>
            </div>
          </div>
        </div>
        <div class="input-group mb-3">
          <input type="password" class="form-control" placeholder="Password">
          <div class="input-group-append">
            <div class="input-group-text">
              <span class="fas fa-lock"></span>
            </div>
          </div>
        </div>
        <div class="input-group mb-3">
          <input type="password" class="form-control" placeholder="Retype password">
          <div class="input-group-append">
            <div class="input-group-text">
              <span class="fas fa-lock"></span>
            </div>
          </div>
        </div>
        <div class="row">
          <div class="col-8">
            <div class="icheck-primary">
              <input type="checkbox" id="agreeTerms" name="terms" value="agree">
              <label for="agreeTerms">
               I agree to the <a href="#">terms</a>
              </label>
            </div>
          </div>
          <!-- /.col -->
          <div class="col-4">
            <button type="submit" class="btn btn-primary btn-block">Register</button>
          </div>
          <!-- /.col -->
        </div>
      </form>

      <div class="social-auth-links text-center">
        <p>- OR -</p>
        <a href="#" class="btn btn-block btn-primary">
          <i class="fab fa-facebook mr-2"></i>
          Sign up using Facebook
        </a>
        <a href="#" class="btn btn-block btn-danger">
          <i class="fab fa-google-plus mr-2"></i>
          Sign up using Google+
        </a>
      </div>

      <a href="login.html" class="text-center">I already have a membership</a>
    </div>
    <!-- /.form-box -->
  </div><!-- /.card -->
</div>
<!-- /.register-box -->

<!-- jQuery -->
<script src="../../plugins/jquery/jquery.min.js"></script>
<!-- Bootstrap 4 -->
<script src="../../plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
<!-- AdminLTE App -->
<script src="../../dist/js/adminlte.min.js"></script>
</body>
</html>